name: brew test

on:
  push:
    branches: [main]
    paths:
      - "Formula/**"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "Formula/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    name: brew install (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-latest-large, ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@master

      - name: brew install --build-from-source
        run: brew install --build-from-source --verbose "${GITHUB_WORKSPACE}/Formula/dcode.rb"

      - name: brew test
        run: brew test --verbose dcode
